// CLI da esteira de merge (CEO 06/10). Só API REST (GraphQL é bloqueado na rede da sessão — mensagem fbad644a).
// Usado pelo gilberto-revisor e pelo workflow fila-merge.yml. Nunca imprime o token.
//   tsx scripts/esteira/esteira.ts patch-id <pr>        id de conteúdo atual da PR
//   tsx scripts/esteira/esteira.ts autorizada <pr>      0 = autorização vale para o conteúdo atual
//   tsx scripts/esteira/esteira.ts pos-migration [pr]   decide e, se cancelado, re-roda o @pos-migration
//   tsx scripts/esteira/esteira.ts fila                 uma passada da fila de merge (um merge por vez)
import { autorizada, decidirPosMigration, idConteudo, idsAutorizados, LABEL_FILA, ordemFila, resumirChecks, temMigration, type Comentario, type PrFila, type RunPos } from './logica'

const REPO = process.env.GITHUB_REPOSITORY ?? 'psgestaoecapital/erp-psgestao'
const TOKEN = process.env.GH_TOKEN ?? process.env.GITHUB_TOKEN ?? ''
const ALLOW = (process.env.ESTEIRA_AUTORIZADORES ?? '').split(',').map((s) => s.trim()).filter(Boolean)
const WF_POS = 'aceitacao-pos-migration.yml'
const WF_DEPLOY = 'deploy-migrations.yml'

async function gh<T = any>(path: string, init: RequestInit & { accept?: string; raw?: boolean } = {}): Promise<T> {
  const r = await fetch(path.startsWith('http') ? path : `https://api.github.com/repos/${REPO}/${path}`, {
    ...init,
    headers: { Authorization: `Bearer ${TOKEN}`, Accept: init.accept ?? 'application/vnd.github+json', 'X-GitHub-Api-Version': '2022-11-28', ...(init.headers ?? {}) },
  })
  if (!r.ok) throw new Error(`${init.method ?? 'GET'} ${path.split('?')[0]} → ${r.status}`)
  if (init.raw) return (await r.text()) as T
  return (r.status === 204 ? null : await r.json()) as T
}
const pages = async <T>(path: string, chave?: string): Promise<T[]> => {
  const out: T[] = []
  for (let p = 1; p <= 10; p++) {
    const j: any = await gh(`${path}${path.includes('?') ? '&' : '?'}per_page=100&page=${p}`)
    const lista: T[] = chave ? j[chave] : j
    out.push(...lista)
    if (lista.length < 100) break
  }
  return out
}
const post = (path: string, body?: unknown) => gh(path, { method: 'POST', body: body ? JSON.stringify(body) : undefined })
const comentar = (n: number, texto: string) =>
  post(`issues/${n}/comments`, { body: `${texto}\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_` })

export const idAtual = async (pr: number) => idConteudo(await gh(`pulls/${pr}`, { accept: 'application/vnd.github.diff', raw: true }))

/** Runs do @pos-migration dos commits da main a partir da última migration (mais novo primeiro). */
async function runsPos(): Promise<RunPos[]> {
  const ult: any[] = await gh('commits?sha=main&path=supabase/migrations&per_page=1')
  if (!ult.length) return []
  const sha = ult[0].sha as string
  const desde = new Date(ult[0].commit.committer.date).getTime()
  const runs = (await gh<any>(`actions/workflows/${WF_POS}/runs?branch=main&per_page=50`)).workflow_runs as any[]
  // run do próprio commit ou de commit posterior (criado depois dele)
  return runs.filter((r) => r.head_sha === sha || new Date(r.created_at).getTime() >= desde).map((r) => ({ id: r.id, head_sha: r.head_sha, status: r.status, conclusion: r.conclusion }))
}

async function posMigration(pr?: number) {
  if (pr) {
    const arq = (await pages<any>(`pulls/${pr}/files`)).map((f) => f.filename as string)
    if (!temMigration(arq)) return { acao: 'liberado', motivo: `PR #${pr} sem migration: não espera o @pos-migration (exige gates + Vercel + aceitação da área)` }
  }
  const d = decidirPosMigration(await runsPos())
  if (d.acao === 'rerun') await post(`actions/runs/${d.runId}/rerun`) // REST, sem GraphQL
  return d
}

async function autorizadaPr(pr: number) {
  const p = await gh<any>(`pulls/${pr}`)
  const coms = await pages<Comentario>(`issues/${pr}/comments`)
  const id = await idAtual(pr)
  const labels = (p.labels as any[]).map((l) => l.name as string)
  return { ok: autorizada(id, coms, pr, labels, ALLOW), id, gravados: idsAutorizados(coms, pr, ALLOW) }
}

/** Uma passada da fila: no máximo UM merge por execução; reentra por evento (checks/runs), sem polling. */
async function fila() {
  if (!TOKEN) throw new Error('sem token')
  const abertas = await pages<any>('pulls?state=open')
  const cand: PrFila[] = []
  for (const p of abertas) {
    if (!p.labels.some((l: any) => l.name === LABEL_FILA)) continue
    const ev = (await pages<any>(`issues/${p.number}/events`)).filter((e) => e.event === 'labeled' && e.label?.name === LABEL_FILA).pop()
    cand.push({ number: p.number, draft: p.draft, labels: p.labels.map((l: any) => l.name), filaDesde: ev?.created_at ?? p.updated_at })
  }
  const fila = ordemFila(cand)
  if (!fila.length) return console.log('fila vazia')
  const n = fila[0].number
  const p = await gh<any>(`pulls/${n}`)
  console.log(`cabeça da fila: #${n} — ${p.title}`)

  // main precisa estar verde/quieta: nenhum deploy-migrations em andamento e @pos-migration não vermelho
  const deploys = (await gh<any>(`actions/workflows/${WF_DEPLOY}/runs?branch=main&per_page=5`)).workflow_runs as any[]
  if (deploys.some((r) => r.status !== 'completed')) return console.log('deploy-migrations em andamento na main — espera o próximo evento')
  const pos = await posMigration(n)
  console.log(`@pos-migration: ${pos.acao} — ${pos.motivo}`)
  if (pos.acao === 'bloqueado') return void (await comentar(n, `⏸️ **Fila de merge parada**: ${pos.motivo}. Nada é mergeado até a main voltar a verde.`))
  if (pos.acao !== 'liberado') return

  const cmp = await gh<any>(`compare/main...${p.head.sha}`)
  if (cmp.behind_by > 0) {
    await gh(`pulls/${n}/update-branch`, { method: 'PUT', body: JSON.stringify({ expected_head_sha: p.head.sha }) })
    return console.log(`#${n} atualizada com a main (${cmp.behind_by} commits atrás); os checks rodam de novo e a fila reentra`)
  }
  const checks = resumirChecks((await gh<any>(`commits/${p.head.sha}/check-runs?per_page=100`)).check_runs)
  if (checks.pendente.length) return console.log(`checks pendentes: ${checks.pendente.join(', ')}`)
  if (!checks.ok) {
    await gh(`issues/${n}/labels/${LABEL_FILA}`, { method: 'DELETE' })
    return void (await comentar(n, `🔴 **Saiu da fila de merge**: checks não verdes (${checks.vermelho.join(', ') || 'nenhum check'}). Corrija, e reponha a label \`${LABEL_FILA}\`.`))
  }
  const aut = await autorizadaPr(n)
  if (!aut.ok) {
    await gh(`issues/${n}/labels/${LABEL_FILA}`, { method: 'DELETE' })
    return void (await comentar(n, `⛔ **Saiu da fila de merge**: sem autorização válida para o conteúdo atual (patch-id \`${aut.id}\`). Autorizações gravadas: ${aut.gravados.map((i) => `\`${i}\``).join(', ') || 'nenhuma'}. O Eng. Chefe revisa e grava \`MERGE AUTORIZADO #${n} · patch-id: \`${aut.id}\`\`, ou a PR leva a label de categoria RD-94.1.`))
  }
  await gh(`pulls/${n}/merge`, { method: 'PUT', body: JSON.stringify({ merge_method: 'squash', sha: p.head.sha }) })
  await comentar(n, `✅ **Mergeada pela fila** (squash, ${p.head.sha.slice(0, 7)}, patch-id \`${aut.id}\`). ${temMigration((await pages<any>(`pulls/${n}/files`)).map((f) => f.filename)) ? 'Tem migration: o veredito é o aceitacao-pos-migration; vermelho = reverter.' : 'Sem migration.'}`)
  console.log(`#${n} mergeada`)
  // merge feito com GITHUB_TOKEN não dispara o push na main: dispara o deploy à mão (com PAT o push já dispara)
  if (process.env.ESTEIRA_DISPARAR_DEPLOY === 'true') await post(`actions/workflows/${WF_DEPLOY}/dispatches`, { ref: 'main' })
}

const [cmd, arg] = process.argv.slice(2)
const num = Number(arg)
const main = async () => {
  if (!TOKEN) throw new Error('GH_TOKEN ausente')
  if (cmd === 'patch-id') console.log(await idAtual(num))
  else if (cmd === 'autorizada') { const r = await autorizadaPr(num); console.log(JSON.stringify(r)); process.exit(r.ok ? 0 : 1) }
  else if (cmd === 'pos-migration') { const d: any = await posMigration(arg ? num : undefined); console.log(JSON.stringify(d)); process.exit(d.acao === 'liberado' ? 0 : 1) }
  else if (cmd === 'fila') await fila()
  else throw new Error('uso: patch-id <pr> | autorizada <pr> | pos-migration [pr] | fila')
}
main().catch((e) => { console.error(`[esteira] ${e.message}`); process.exit(2) })
