-- RD-95 na GE (caixa jordana-code 267a1555): "?" de todos os campos de Nova despesa, Nova receita e da chave PIX.
-- Os formulários também abrem em modal (contas a pagar/receber, conciliação), por isso cada um usa a rota da sua tela
-- ('/dashboard/financeiro/nova-despesa' e '/nova-receita') e a chave PIX, que aparece nos dois, uma rota própria.
-- Aditivo: só INSERT de textos (ON CONFLICT DO NOTHING); nenhuma tabela, função ou permissão nova.
INSERT INTO public.erp_ajuda_campo (chave, grupo, rotulo, o_que_preencher, para_que_serve, exemplo, erro_comum, ordem, rota, vertical, status)
SELECT v.chave, 'Financeiro · Nova despesa', v.rotulo, v.o_que, v.para_que, v.exemplo, v.erro, v.ordem,
       '/dashboard/financeiro/nova-despesa', 'gestao_empresarial', 'publicado'
FROM (VALUES
 ('financeiro.despesa.descricao', 'O que é essa despesa?', 'Um nome curto que você reconheça no contas a pagar. Pode deixar vazio: o sistema usa "fornecedor — categoria".', 'É o texto que aparece na lista, no extrato conciliado e nos relatórios.', 'Aluguel da sala — maio', 'Escrever o valor ou a data aqui: eles têm campo próprio e a busca fica confusa.', 10),
 ('financeiro.despesa.valor', 'Quanto custa?', 'O valor total da conta em reais, com centavos. Com parcelas, escolha abaixo se é o total ou o valor de cada parcela.', 'É o valor a pagar que entra no fluxo de caixa no vencimento e no DRE na competência.', '1.250,00', 'Lançar o valor já com juros de atraso: juros e multa entram na baixa, não no valor da conta.', 11),
 ('financeiro.despesa.vencimento', 'Quando vence?', 'A data de vencimento que está no boleto, na nota ou no combinado com o fornecedor.', 'Define o dia em que a saída aparece no fluxo de caixa e quando a conta fica atrasada.', '10/11/2026', 'Usar a data de hoje para tudo: o fluxo de caixa fica todo concentrado num dia só.', 12),
 ('financeiro.despesa.competencia', 'Data de competência', 'O mês a que a despesa pertence de verdade (quando o serviço foi usado). Vazio = mesma data do vencimento.', 'O DRE soma a despesa no mês da competência, não no mês do pagamento.', 'Conta de luz de outubro que vence em 10/11 → competência 31/10', 'Deixar vazio em conta que vence no mês seguinte: o custo cai no mês errado do DRE.', 13),
 ('financeiro.despesa.fornecedor', 'Para quem você paga?', 'Escolha o fornecedor da lista. Se não estiver, escolha "Outro" e digite o nome: ele fica cadastrado ao salvar.', 'Agrupa os gastos por fornecedor e ajuda a achar conta lançada em dobro.', 'Celesc Distribuição', 'Digitar o nome de novo de um jeito diferente ("Celesc" e "CELESC SA"): o fornecedor vira dois cadastros.', 14),
 ('financeiro.despesa.categoria', 'Categoria do DRE', 'Digite parte do nome e escolha a categoria do plano de contas. Se não existir, dá para criar ali mesmo.', 'É a linha do DRE onde a despesa entra (custo, despesa administrativa, imposto etc.).', 'Energia elétrica', 'Jogar tudo em "Outras despesas": o DRE perde a leitura de onde o dinheiro está indo.', 15),
 ('financeiro.despesa.centro_custo', 'Centro de custo / obra', 'Escolha o setor, filial ou obra que gerou o gasto. Pode ficar sem.', 'Separa o custo por centro: o gasto da obra aparece na ficha da obra no Hub e no DRE por centro.', 'Obra Residencial Ipê', 'Deixar sem centro um gasto de obra: o custo da obra fica menor do que foi.', 16),
 ('financeiro.despesa.parcelas', 'Quantas parcelas?', 'Em quantas vezes a conta vai ser paga. 1 = à vista.', 'Cria um título a pagar para cada parcela, cada um com seu vencimento.', '3', 'Lançar cada parcela à mão como despesa separada: some o vínculo entre elas.', 17),
 ('financeiro.despesa.intervalo', 'Intervalo entre parcelas', 'De quanto em quanto tempo vence cada parcela.', 'Calcula o vencimento das parcelas a partir do primeiro vencimento.', 'Mensal (30 dias)', 'Escolher "Mensal" quando o boleto vence sempre no mesmo dia: use também o "Dia do vencimento".', 18),
 ('financeiro.despesa.dia_fixo', 'Dia do vencimento', 'O dia do mês em que todas as parcelas vencem. Vazio = conta os dias corridos do intervalo.', 'Mantém as parcelas no mesmo dia todo mês; em mês sem o dia (31 em fevereiro) vai para o último dia.', '10', 'Deixar vazio em parcelamento mensal: as datas vão escorregando (30 dias não é um mês).', 19),
 ('financeiro.despesa.parcela_vencimento', 'Vencimento da parcela', 'A data de cada parcela. Já vem calculada; ajuste a que for diferente.', 'Cada parcela entra no fluxo de caixa na sua data.', '2ª parcela em 10/12/2026', 'Mudar o 1º vencimento depois de ajustar as parcelas: confira as datas de novo.', 20),
 ('financeiro.despesa.parcela_valor', 'Valor da parcela', 'O valor de cada parcela. Já vem dividido; ajuste a que for diferente (entrada maior, por exemplo).', 'A soma das parcelas é o total da conta; o aviso amarelo mostra quando não bate.', '500,00 + 375,00 + 375,00', 'Ignorar o aviso de soma diferente: o total a pagar fica errado.', 21),
 ('financeiro.despesa.forma', 'Como você vai pagar?', 'A forma de pagamento: boleto, PIX, cartão, débito automático, dinheiro etc.', 'Com PIX pede a chave; com cartão de crédito calcula em qual fatura a compra cai.', 'Boleto', 'Marcar cartão de crédito numa conta paga no boleto: o vencimento passa a seguir a fatura.', 22),
 ('financeiro.despesa.conta', 'Em qual conta sai o dinheiro?', 'A conta bancária (ou caixa) de onde o pagamento vai sair. Pode escolher depois.', 'É a conta que tem o saldo diminuído na baixa e onde a conciliação procura o movimento do extrato.', 'Sicredi — conta movimento', 'Escolher a conta errada: na conciliação o pagamento não aparece no extrato certo.', 23),
 ('financeiro.despesa.data_compra', 'Data da compra (cartão)', 'O dia em que a compra foi feita no cartão de crédito.', 'Com o fechamento do cartão, o sistema acha a fatura e preenche o vencimento sozinho.', '28/10/2026', 'Colocar a data do vencimento da fatura: a compra pode ir para a fatura errada.', 24),
 ('financeiro.despesa.documento', 'Número do documento', 'O número da nota fiscal, do boleto ou do contrato que comprova a conta.', 'Ajuda a achar a conta e a evitar lançamento em dobro.', 'NF 12345', 'Deixar vazio quando há nota: fica difícil provar a despesa na auditoria.', 25),
 ('financeiro.despesa.codigo_barras', 'Código de barras', 'Cole a linha digitável ou passe o leitor no boleto ou na guia de imposto.', 'Reconhece o valor e o vencimento, avisa se essa conta já foi lançada e vai para a remessa de pagamento.', '23793.38128 60000.000003 ...', 'Digitar à mão com um número errado: o aviso de conta repetida não funciona.', 26),
 ('financeiro.despesa.observacao', 'Observação', 'Qualquer detalhe que ajude quem for pagar ou conferir depois.', 'Fica guardada no título; não muda valores.', 'Pagar só depois da entrega do material', 'Colocar aqui valores de juros ou desconto: use os campos próprios.', 27),
 ('financeiro.despesa.juros', 'Juros', 'Juros cobrados por atraso, em reais.', 'Somam ao valor pago e vão para a conta de juros do DRE.', '12,50', 'Somar os juros no valor da conta: o custo original fica maior do que foi.', 28),
 ('financeiro.despesa.multa', 'Multa', 'Multa cobrada por atraso, em reais.', 'Soma ao valor pago, separada do valor original.', '25,00', 'Lançar a multa como desconto negativo.', 29),
 ('financeiro.despesa.desconto', 'Desconto', 'Desconto que o fornecedor deu, em reais.', 'Diminui o valor pago, sem mudar o valor original da conta.', '50,00', 'Diminuir o valor da conta em vez de lançar o desconto: perde-se o registro do desconto obtido.', 30),
 ('financeiro.despesa.ja_pago', 'Já paguei', 'Marque se essa conta já foi paga. Com parcelas, marca só a 1ª.', 'Lança a despesa já baixada, com a data do pagamento e a conta escolhida.', 'Marcado para a conta de luz paga hoje no app do banco', 'Marcar sem escolher a conta bancária: o pagamento não tem de onde sair.', 31),
 ('financeiro.despesa.data_pagamento', 'Data do pagamento', 'O dia em que o dinheiro saiu da conta.', 'É a data da baixa: entra no saldo da conta e no fluxo realizado nesse dia.', '09/10/2026', 'Usar a data do vencimento quando pagou em outro dia: o extrato não bate na conciliação.', 32),
 ('financeiro.despesa.copiar_busca', 'Buscar despesa para copiar', 'Digite parte da descrição, do fornecedor ou da categoria de uma despesa já lançada.', 'Copia os dados da despesa escolhida para não digitar tudo de novo.', 'aluguel', 'Copiar e não trocar o vencimento: a nova conta nasce com a data da antiga.', 33)
) AS v(chave, rotulo, o_que, para_que, exemplo, erro, ordem)
ON CONFLICT (chave) DO NOTHING;

INSERT INTO public.erp_ajuda_campo (chave, grupo, rotulo, o_que_preencher, para_que_serve, exemplo, erro_comum, ordem, rota, vertical, status)
SELECT v.chave, 'Financeiro · Nova receita', v.rotulo, v.o_que, v.para_que, v.exemplo, v.erro, v.ordem,
       '/dashboard/financeiro/nova-receita', 'gestao_empresarial', 'publicado'
FROM (VALUES
 ('financeiro.receita.descricao', 'O que é essa receita?', 'Um nome curto que você reconheça no contas a receber. Pode deixar vazio: o sistema monta um nome.', 'É o texto que aparece na lista, no extrato conciliado e nos relatórios.', 'Mensalidade outubro — Cliente X', 'Escrever o valor ou a data aqui: eles têm campo próprio.', 10),
 ('financeiro.receita.valor', 'Quanto vou receber?', 'O valor bruto a receber em reais. No cartão, a taxa da maquininha é descontada sozinha.', 'É o valor que entra no fluxo de caixa e no faturamento do DRE.', '2.400,00', 'Lançar já o valor líquido do cartão: a taxa some do DRE e o faturamento fica menor.', 11),
 ('financeiro.receita.recebimento', 'Quando entra na conta?', 'A data prevista do recebimento (vencimento do boleto, data do PIX combinado).', 'Define o dia em que a entrada aparece no fluxo de caixa e quando fica em atraso.', '15/11/2026', 'Usar a data da venda quando o cliente paga depois: o fluxo de caixa mostra dinheiro que ainda não entrou.', 12),
 ('financeiro.receita.competencia', 'Data de competência', 'O mês em que a venda ou o serviço aconteceu. Vazio = mesma data do recebimento.', 'O DRE soma a receita no mês da competência, não no mês em que o dinheiro entra.', 'Serviço de outubro recebido em 10/11 → competência 31/10', 'Deixar vazio em venda a prazo: o faturamento cai no mês errado do DRE.', 13),
 ('financeiro.receita.cliente', 'De quem você vai receber?', 'Digite e escolha o cliente. Se não existir, dá para cadastrar ali mesmo.', 'Liga a receita ao cliente: inadimplência, cobrança e boletos saem daqui.', 'Mecânica Exemplo Ltda', 'Cadastrar o mesmo cliente de novo com outro nome: os recebimentos ficam divididos.', 14),
 ('financeiro.receita.categoria', 'Categoria do DRE', 'Digite parte do nome e escolha a categoria de receita do plano de contas.', 'É a linha do DRE onde a receita entra (venda de produtos, serviços, financeira etc.).', 'Receita de serviços', 'Lançar empréstimo ou aporte como receita de vendas: o faturamento fica inflado.', 15),
 ('financeiro.receita.parcelas', 'Quantas parcelas?', 'Em quantas vezes o cliente vai pagar. 1 = à vista.', 'Cria um título a receber para cada parcela, cada um com seu vencimento.', '4', 'Lançar cada parcela à mão como receita separada: some o vínculo entre elas.', 16),
 ('financeiro.receita.intervalo', 'Intervalo entre parcelas', 'De quanto em quanto tempo vence cada parcela.', 'Calcula o vencimento das parcelas a partir da primeira data.', 'Mensal (30 dias)', 'Escolher "Mensal" quando o cliente paga sempre no mesmo dia: use também o "Dia do vencimento".', 17),
 ('financeiro.receita.dia_fixo', 'Dia do vencimento', 'O dia do mês em que todas as parcelas vencem. Vazio = conta os dias corridos do intervalo.', 'Mantém as parcelas no mesmo dia todo mês; em mês sem o dia vai para o último dia.', '5', 'Deixar vazio em parcelamento mensal: as datas vão escorregando (30 dias não é um mês).', 18),
 ('financeiro.receita.parcela_vencimento', 'Vencimento da parcela', 'A data de cada parcela. Já vem calculada; ajuste a que for diferente.', 'Cada parcela entra no fluxo de caixa na sua data.', '3ª parcela em 05/01/2027', 'Mudar a primeira data depois de ajustar as parcelas: confira as datas de novo.', 19),
 ('financeiro.receita.parcela_valor', 'Valor da parcela', 'O valor de cada parcela. Já vem dividido; ajuste a que for diferente (entrada, por exemplo).', 'A soma das parcelas é o total a receber; o aviso amarelo mostra quando não bate.', '1.000,00 + 700,00 + 700,00', 'Ignorar o aviso de soma diferente: o total a receber fica errado.', 20),
 ('financeiro.receita.forma', 'Como você vai receber?', 'A forma de recebimento: boleto, PIX, cartão, dinheiro, transferência etc.', 'Com cartão pede a maquininha e calcula taxa e data do repasse; com PIX pede a chave.', 'PIX', 'Marcar PIX numa venda no cartão: a taxa da maquininha não é descontada e o saldo não bate.', 21),
 ('financeiro.receita.adquirente', 'Adquirente (maquininha)', 'A empresa da maquininha que passou o cartão. As taxas vêm do cadastro em Cartões / Adquirentes.', 'Escolhe a tabela de taxas e o prazo de repasse usados no cálculo do líquido.', 'Stone', 'Escolher outra maquininha: a taxa e a data do dinheiro na conta ficam erradas.', 22),
 ('financeiro.receita.bandeira', 'Bandeira', 'A bandeira do cartão do cliente.', 'Cada bandeira tem sua taxa na maquininha.', 'Visa', 'Escolher qualquer bandeira para ir mais rápido: a taxa descontada fica diferente da real.', 23),
 ('financeiro.receita.modalidade', 'Modalidade', 'Débito, crédito à vista ou crédito parcelado.', 'Define a taxa e em quantos dias o dinheiro cai na conta (D+1, D+30...).', 'Crédito à vista', 'Marcar débito numa venda no crédito: o recebimento aparece semanas antes no fluxo.', 24),
 ('financeiro.receita.conta', 'Em qual conta entra o dinheiro?', 'A conta bancária (ou caixa) onde o dinheiro vai cair.', 'É a conta que tem o saldo aumentado na baixa e onde a conciliação procura o movimento do extrato.', 'Banco do Brasil — conta movimento', 'Escolher a conta errada: na conciliação o recebimento não aparece no extrato certo.', 25),
 ('financeiro.receita.centro_custo', 'Centro de custo', 'O setor, filial ou obra a que a receita pertence. Pode ficar sem.', 'Separa o faturamento por centro no DRE por centro de custo.', 'Filial Chapecó', 'Deixar sem centro quando a empresa analisa o resultado por filial ou obra.', 26),
 ('financeiro.receita.documento', 'Número do documento', 'O número da nota fiscal, do pedido ou do contrato da venda.', 'Ajuda a achar a receita e a ligar com a nota emitida.', 'NF 4567', 'Deixar vazio quando há nota: fica difícil cobrar e conferir depois.', 27),
 ('financeiro.receita.observacao', 'Observação', 'Qualquer detalhe que ajude a cobrar ou conferir depois.', 'Fica guardada no título; não muda valores.', 'Cliente pediu boleto para o dia 15', 'Colocar aqui juros ou desconto: use os campos próprios.', 28),
 ('financeiro.receita.juros', 'Juros', 'Juros recebidos do cliente por atraso, em reais.', 'Somam ao valor recebido e vão para receita financeira no DRE.', '18,00', 'Somar os juros no valor da venda: o faturamento fica maior do que foi.', 29),
 ('financeiro.receita.multa', 'Multa', 'Multa recebida do cliente por atraso, em reais.', 'Soma ao valor recebido, separada do valor original.', '48,00', 'Lançar a multa como desconto negativo.', 30),
 ('financeiro.receita.desconto', 'Desconto', 'Desconto dado ao cliente no recebimento, em reais.', 'Diminui o valor recebido, sem mudar o valor original da venda.', '100,00', 'Diminuir o valor da venda em vez de lançar o desconto: perde-se o registro do desconto concedido.', 31),
 ('financeiro.receita.ja_recebido', 'Já recebi', 'Marque se o dinheiro já entrou. Com parcelas, marca só a 1ª.', 'Lança a receita já baixada, com a data do recebimento e a conta escolhida.', 'Marcado para venda à vista no PIX', 'Marcar sem escolher a conta: o recebimento não tem onde entrar.', 32),
 ('financeiro.receita.data_recebimento', 'Data do recebimento', 'O dia em que o dinheiro entrou na conta.', 'É a data da baixa: entra no saldo da conta e no fluxo realizado nesse dia.', '09/10/2026', 'Usar a data da venda quando o dinheiro caiu depois: o extrato não bate na conciliação.', 33)
) AS v(chave, rotulo, o_que, para_que, exemplo, erro, ordem)
ON CONFLICT (chave) DO NOTHING;

INSERT INTO public.erp_ajuda_campo (chave, grupo, rotulo, o_que_preencher, para_que_serve, exemplo, erro_comum, ordem, rota, vertical, status)
SELECT v.chave, 'Financeiro · Chave PIX', v.rotulo, v.o_que, v.para_que, v.exemplo, v.erro, v.ordem,
       '/dashboard/financeiro/chave-pix', 'gestao_empresarial', 'publicado'
FROM (VALUES
 ('financeiro.pix.tipo_chave', 'Tipo de chave PIX', 'Escolha o tipo da chave: CPF/CNPJ, telefone, e-mail, chave aleatória ou PIX copia e cola.', 'Define a máscara e a conferência da chave digitada.', 'CPF/CNPJ', 'Escolher telefone e colar um e-mail: a chave é recusada.', 10),
 ('financeiro.pix.chave', 'Chave PIX', 'A chave PIX de quem recebe (ou o código copia e cola inteiro).', 'Vai para a remessa de pagamento ao banco; chave errada = pagamento para outra pessoa.', '12.345.678/0001-90', 'Copiar a chave de uma mensagem antiga sem conferir com o fornecedor.', 11)
) AS v(chave, rotulo, o_que, para_que, exemplo, erro, ordem)
ON CONFLICT (chave) DO NOTHING;
