-- P&M · Equipe: "Carga × capacidade" (onda 3 da P&M da Pdois, mapeamento do SIGA, Parte S) e o "?" dos campos do cadastro
-- da equipe (RD-95). Aditiva: só texto de ajuda novo; sem dado de cliente.
INSERT INTO public.erp_ajuda_campo (chave, grupo, rotulo, o_que_preencher, para_que_serve, exemplo, erro_comum, ordem, rota, vertical, status)
SELECT v.chave, v.grupo, v.rotulo, v.o_que, v.para_que, v.exemplo, v.erro, v.ordem, v.rota, 'pm', 'publicado'
FROM (VALUES
 ('pm.equipe.nome', 'Equipe', 'Nome', 'O nome da pessoa como a equipe a chama. Se ela também usa o sistema, escreva igual ao nome do usuário dela.', 'É por ele que a carga encontra a pessoa quando o cadastro não está ligado a um usuário.', 'Ana Paula Souza', 'Abreviar ("Ana P.") quando o usuário se chama "Ana Paula Souza": a carga não reconhece e mostra a pessoa como fora da equipe.', 1, '/dashboard/pm/equipe'),
 ('pm.equipe.cargo', 'Equipe', 'Cargo', 'A função da pessoa na agência.', 'Ajuda a ler a carga: quem está sobrecarregado e em qual função falta gente.', 'Diretora de arte', 'Deixar vazio: a lista fica só com nomes e fica difícil redistribuir o trabalho.', 2, '/dashboard/pm/equipe'),
 ('pm.equipe.setor', 'Equipe', 'Setor', 'A área em que a pessoa trabalha.', 'Agrupa a equipe por área (criação, atendimento, mídia).', 'Criação', 'Escrever o mesmo setor de jeitos diferentes ("Criação" e "criacao").', 3, '/dashboard/pm/equipe'),
 ('pm.equipe.custo_hora', 'Equipe', 'Custo/hora (R$)', 'Quanto uma hora dessa pessoa custa para a agência (salário + encargos + benefícios, dividido pelas horas do mês).', 'É a base da margem por job: horas apontadas × custo/hora. Só quem vê salário enxerga e edita.', 'Salário + encargos R$ 6.600 ÷ 176 h = R$ 37,50/h', 'Usar só o salário: a margem fica maior do que a real.', 4, '/dashboard/pm/equipe'),
 ('pm.equipe.jornada', 'Equipe', 'Jornada (h/dia)', 'Quantas horas por dia a pessoa trabalha nos jobs.', 'É a capacidade da pessoa na "Carga × capacidade": jornada × dias úteis do período.', '8 h/dia × 5 dias úteis = 40 h na semana', 'Pôr a jornada do contrato quando parte do dia vai para reuniões internas: a capacidade parece maior do que é.', 5, '/dashboard/pm/equipe'),
 ('pm.equipe.ativo', 'Equipe', 'Ativo', 'Desmarque quando a pessoa sai da agência.', 'Quem está inativo sai da capacidade da equipe, mas o histórico de horas fica.', 'Estagiário que terminou o contrato: desmarque.', 'Apagar a pessoa em vez de inativar: some o histórico.', 6, '/dashboard/pm/equipe'),
 ('pm.equipe.carga', 'Carga', 'Carga × capacidade', 'Nada a preencher: a tela soma o trabalho aberto de cada pessoa e compara com a jornada dela no período.', 'Mostra quem está acima da capacidade e quem tem folga, para redistribuir antes de atrasar.', 'Ana: 46 h de 40 h (115%) — acima da capacidade; Bruno: 12 h de 40 h — com folga.', 'Achar que conta as horas já feitas: conta só o que falta fazer (estimado − realizado) das tarefas e jobs abertos.', 10, '/dashboard/pm/equipe'),
 ('pm.equipe.carga_periodo', 'Carga', 'Período', 'Toque em Esta semana, 2 semanas ou 4 semanas.', 'Define a janela a partir de hoje. Trabalho com prazo dentro dela (ou vencido) conta inteiro; com prazo depois, conta só a parte proporcional.', 'Job de 20 h com prazo daqui a 10 dias úteis: na semana (5 dias úteis) entram 10 h.', 'Comparar semanas diferentes sem trocar o período.', 11, '/dashboard/pm/equipe'),
 ('pm.equipe.carga_capacidade', 'Carga', 'Capacidade', 'Nada a preencher: soma da jornada de cada pessoa ativa × dias úteis (segunda a sexta) do período.', 'É o total de horas que a equipe consegue entregar no período.', '3 pessoas × 8 h × 5 dias úteis = 120 h', 'Esquecer a jornada no cadastro: a pessoa entra com 8 h/dia (padrão).', 12, '/dashboard/pm/equipe'),
 ('pm.equipe.carga_comprometido', 'Carga', 'Comprometido', 'Nada a preencher: horas que faltam (estimado − realizado) das tarefas e jobs abertos que caem no período.', 'Mostra quanto da capacidade já está tomado. Tarefa com estimativa vale para o responsável dela; job sem tarefas estimadas vale para o responsável do job.', 'Tarefa de 6 h com 2 h já apontadas: entram 4 h.', 'Job sem horas estimadas não entra: estime as horas no job ou nas tarefas.', 13, '/dashboard/pm/equipe'),
 ('pm.equipe.carga_previsao', 'Carga', 'Previsão', 'Nada a preencher: horas das propostas enviadas e das aprovadas que ainda não viraram job, mais as horas mensais dos fees ativos proporcionais ao período.', 'Antecipa o trabalho que está vindo, antes de existir job, para planejar contratação ou freelancer.', 'Proposta enviada com 30 h + fee de 40 h/mês (na semana, ~9 h) = previsão de 39 h.', 'Proposta sem horas estimadas nos itens não entra na previsão.', 14, '/dashboard/pm/equipe'),
 ('pm.equipe.carga_livre', 'Carga', 'Livre', 'Nada a preencher: capacidade − comprometido − previsão.', 'Negativo (vermelho) quer dizer que o trabalho que já existe e o que está vindo não cabem na equipe no período.', '120 h − 95 h − 39 h = −14 h (faltam 14 h)', 'Ler "livre" como horas ociosas garantidas: a previsão ainda pode não se confirmar.', 15, '/dashboard/pm/equipe')
) AS v(chave, grupo, rotulo, o_que, para_que, exemplo, erro, ordem, rota)
WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'erp_ajuda_campo')
ON CONFLICT (chave) DO NOTHING;
