-- Chamado #2254 (Rodrigo) · RD-95: "?" dos campos da tela Renegociação / Acerto (juros e multa, boleto, WhatsApp). Só dados de ajuda.
INSERT INTO public.erp_ajuda_campo (chave, grupo, rotulo, o_que_preencher, para_que_serve, exemplo, erro_comum, ordem, rota, vertical, status)
VALUES
  ('financeiro.renegociacao.cliente', 'Renegociação / Acerto', 'Cliente', 'Escolha o cliente cujos títulos serão renegociados. Em branco = todos os clientes da empresa.', 'Filtra a lista de títulos abertos; o acerto e o boleto novo ficam no nome do cliente escolhido.', 'Casa Verde Ltda', 'Deixar em branco e selecionar títulos de clientes diferentes: o acerto é de um cliente só.', 10, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.conta', 'Renegociação / Acerto', 'Conta', 'Conta bancária dos títulos que você quer buscar. Em branco = todas.', 'Filtra os títulos pela conta; a conta escolhida também vai para as parcelas novas.', 'Bradesco 1234-5', 'Escolher a conta errada e não ver os títulos que esperava.', 20, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.titulo', 'Renegociação / Acerto', 'Selecionar título', 'Marque os títulos abertos ou vencidos que entram no acerto.', 'A soma dos marcados é a origem. Os vencidos ganham juros e multa de atraso; os marcados viram "renegociado".', 'Duplicata 123 vencida há 20 dias', 'Marcar título que o cliente já pagou: confira a baixa antes.', 30, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.qtd', 'Renegociação / Acerto', 'Qtd. parcelas', 'Em quantas parcelas o total será dividido (1 a 60).', 'Divide o total consolidado (origem + juros + multa) pela quantidade; a última parcela absorve os centavos.', '3', 'Esquecer de clicar em Gerar depois de mudar a quantidade.', 40, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.forma_padrao', 'Renegociação / Acerto', 'Forma padrão', 'Forma de pagamento aplicada a todas as parcelas geradas.', 'Só parcelas em boleto podem ter o boleto emitido aqui; as outras formas ficam registradas.', 'Boleto', 'Escolher PIX e esperar um boleto: só a forma Boleto emite boleto.', 50, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.parcela_valor', 'Renegociação / Acerto', 'Valor da parcela', 'Valor em reais desta parcela.', 'A soma das parcelas é o valor gerado; diferença para a origem exige motivo.', '1.250,00', 'Digitar ponto no lugar da vírgula dos centavos.', 60, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.parcela_vencimento', 'Renegociação / Acerto', 'Vencimento da parcela', 'Data de vencimento desta parcela.', 'Define quando o cliente deve pagar; as datas não podem voltar no tempo entre parcelas.', '15/11/2026', 'Errar o ano da data: o sistema recusa data antes da parcela anterior.', 70, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.parcela_forma', 'Renegociação / Acerto', 'Forma da parcela', 'Forma de pagamento desta parcela especificamente.', 'Permite acerto misto (entrada em dinheiro + restante em boleto).', 'Dinheiro', 'Deixar boleto numa parcela paga à vista.', 80, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.motivo', 'Renegociação / Acerto', 'Motivo do ajuste', 'Explique por que o valor gerado difere da origem. Vem preenchido quando a diferença é juros e multa de atraso.', 'Fica gravado no acerto para auditoria.', 'Juros e multa de atraso', 'Deixar em branco: o sistema não confirma acerto com ajuste sem motivo.', 90, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.juros', 'Renegociação / Acerto', 'Juros de mora (R$)', 'Valor dos juros do atraso deste título. Vem calculado pela taxa do banco; você pode corrigir.', 'Juros ao mês ÷ 30 × dias de atraso, sobre o valor do título (respeita a carência do banco). Soma no total consolidado.', 'R$ 15,00 para 15 dias a 3% ao mês sobre R$ 1.000', 'Sem taxa no banco o campo nasce em 0: informe na mão ou cadastre em Conexões Bancárias.', 100, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.multa', 'Renegociação / Acerto', 'Multa por atraso (R$)', 'Valor da multa deste título. Vem calculado pela taxa do banco; você pode corrigir.', 'Percentual da multa aplicado uma vez sobre o valor do título vencido. Soma no total consolidado.', 'R$ 20,00 para 2% sobre R$ 1.000', 'Cobrar multa de título que ainda está na carência.', 110, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado'),
  ('financeiro.renegociacao.whatsapp', 'Renegociação / Acerto', 'Enviar por WhatsApp', 'Abre o WhatsApp com a mensagem pronta: nome, valor, vencimento, linha digitável e link do boleto.', 'Você envia pelo seu aparelho; o sistema não dispara nada sozinho. Só funciona com o boleto já registrado no banco.', 'Boleto gerado → Enviar por WhatsApp', 'Clicar antes de gerar o boleto: avisa que ainda não está registrado.', 120, '/dashboard/financeiro/renegociacao', 'financeiro', 'publicado')
ON CONFLICT (chave) DO NOTHING;
