-- RD-95: "?" do bloco "Falta no cadastro do tomador" da emissão de NFS-e (TomadorEnderecoPendente, caixa jordana-code
-- 25fac6b6 item 4 — carteira Pdois/Gean). O bloco aparece quando o tomador está no cadastro sem o código IBGE do
-- município (ou sem logradouro/número): pede o CEP ou cidade + UF ali mesmo e grava no cliente.
-- Aditivo: só INSERT de textos (ON CONFLICT DO NOTHING); nenhuma tabela, função ou permissão nova.
INSERT INTO public.erp_ajuda_campo (chave, grupo, rotulo, o_que_preencher, para_que_serve, exemplo, erro_comum, ordem, rota, vertical, status)
SELECT v.chave, 'Emissão de NFS-e · endereço do tomador', v.rotulo, v.o_que, v.para_que, v.exemplo, v.erro, v.ordem,
       '/dashboard/fiscal/nfse/tomador-endereco', 'fiscal', 'publicado'
FROM (VALUES
 ('fiscal.nfse.tomador.cep', 'CEP do tomador', 'Os 8 números do CEP do cliente. Clique em Buscar: rua, bairro, cidade, UF e o código do município vêm sozinhos.', 'A NFS-e nacional exige o município do tomador pelo código IBGE; o CEP é o jeito mais seguro de achar.', '79950-000', 'Usar o CEP da sua empresa em vez do CEP do cliente.', 10),
 ('fiscal.nfse.tomador.logradouro', 'Logradouro', 'Rua, avenida ou estrada do cliente, sem o número.', 'Vai no endereço do tomador na nota.', 'Rua Bertila Friedrich', 'Colocar o número aqui: use o campo Número.', 11),
 ('fiscal.nfse.tomador.numero', 'Número', 'O número do endereço do cliente. Sem número, escreva S/N.', 'A NFS-e nacional não aceita tomador sem número.', '31', 'Deixar vazio: a emissão para pedindo o número.', 12),
 ('fiscal.nfse.tomador.bairro', 'Bairro', 'O bairro do cliente (vem do CEP quando o CEP é de rua).', 'Completa o endereço do tomador na nota.', 'Centro', 'CEP de cidade inteira não traz bairro: digite à mão.', 13),
 ('fiscal.nfse.tomador.cidade', 'Cidade', 'O nome oficial da cidade do cliente, sem abreviar. Vem do CEP.', 'Com a UF, acha o código IBGE do município quando o CEP não resolve.', 'Naviraí', 'Abreviar ("S. Miguel"): o município não é encontrado.', 14),
 ('fiscal.nfse.tomador.uf', 'UF', 'A sigla do estado do cliente, com 2 letras.', 'Com a cidade, acha o código IBGE do município.', 'MS', 'Trocar a UF da cidade: o município não é encontrado.', 15),
 ('fiscal.nfse.tomador.ibge', 'Código IBGE do município', 'Não digite: ele vem do CEP ou de "Achar pela cidade", conferido na tabela oficial dos municípios.', 'É o código do município do tomador que a NFS-e nacional exige; sem ele a nota não sai.', '5005707 (Naviraí/MS)', 'Emitir sem ele: a emissão para em "Complete o cadastro fiscal do tomador".', 16),
 ('fiscal.nfse.tomador.gravar', 'Gravar no cliente', 'Clique depois de preencher o CEP (ou cidade e UF) e o número.', 'Salva o endereço no cadastro do cliente; esta e as próximas notas já saem com ele.', 'Gravar → "Endereço gravado no cadastro do cliente"', 'Fechar a tela sem gravar: na próxima nota o sistema pede de novo.', 17)
) AS v(chave, rotulo, o_que, para_que, exemplo, erro, ordem)
ON CONFLICT (chave) DO NOTHING;

-- RD-95: "?" dos campos do modal de emissão de NFS-e (NFSeEmitirGovModal). O modal abre em várias telas (OS, pedido,
-- contas a receber, lista de NFS-e) e usa a rota de ajuda própria '/dashboard/fiscal/nfse/emitir'. Aditivo.
INSERT INTO public.erp_ajuda_campo (chave, grupo, rotulo, o_que_preencher, para_que_serve, exemplo, erro_comum, ordem, rota, vertical, status)
SELECT v.chave, 'Emissão de NFS-e', v.rotulo, v.o_que, v.para_que, v.exemplo, v.erro, v.ordem,
       '/dashboard/fiscal/nfse/emitir', 'fiscal', 'publicado'
FROM (VALUES
 ('fiscal.nfse.emitir.tomador_documento', 'Tomador (CNPJ/CPF)', 'Escolha CNPJ ou CPF e digite o documento de quem contratou o serviço. Clique em Buscar: o nome e o endereço vêm do cadastro de clientes (ou da Receita).', 'Identifica o tomador na nota; o endereço fiscal (município e número) sai do cadastro do cliente com esse documento.', '12.345.678/0001-90', 'Emitir para o CNPJ de outra filial do cliente: confira os 4 números depois da barra.', 10),
 ('fiscal.nfse.emitir.tomador_nome', 'Razão social / Nome', 'O nome oficial do tomador. Vem sozinho ao buscar o documento; confira.', 'É o nome que sai na nota.', 'Laboratório Costa Rosa Ltda', 'Usar o apelido do cliente: a nota sai com nome diferente do CNPJ.', 11),
 ('fiscal.nfse.emitir.servico', 'Serviço cadastrado', 'Escolha o serviço do cadastro. Ele traz descrição, valor, código de tributação, alíquota e as retenções.', 'As retenções federais e o ISS retido da nota saem do cadastro do serviço; sem serviço a nota não sai.', '01 · Consultoria mensal', 'Escolher um serviço parecido com outras retenções: o valor a receber fica errado.', 12),
 ('fiscal.nfse.emitir.medicao_financeiro', 'Gerar o financeiro da medição', 'Marcado: quando a prefeitura autorizar, as parcelas marcadas viram contas a receber. Desmarcado: ficam previstas.', 'Liga a nota da medição ao contas a receber sem você lançar à mão.', 'Marcado', 'Desmarcar e esquecer de gerar depois: o recebimento não aparece no fluxo.', 13),
 ('fiscal.nfse.emitir.descricao', 'Descrição do serviço', 'O que foi feito, como deve aparecer na nota para o cliente.', 'É o texto do serviço na NFS-e.', 'Serviço de manutenção do equipamento X — setembro/2026', 'Deixar uma descrição genérica ("serviços"): o cliente pode recusar a nota.', 14),
 ('fiscal.nfse.emitir.valor', 'Valor (R$)', 'O valor total do serviço desta nota, com vírgula nos centavos.', 'Base do ISS e das retenções; o líquido a receber sai dele.', '1.500,00', 'Digitar o valor líquido (já sem retenções): a nota sai menor que o contratado.', 15),
 ('fiscal.nfse.emitir.aliquota_iss', 'Alíquota ISS (%)', 'A alíquota do ISS do município para este serviço. Vem do cadastro do serviço.', 'Calcula o ISS destacado na nota (fora do Simples Nacional).', '2', 'Usar a alíquota de outro município: a prefeitura pode rejeitar a nota.', 16),
 ('fiscal.nfse.emitir.observacoes', 'Informações complementares', 'Texto livre que vai nos dados adicionais da nota: CNO da obra, dados bancários, observações.', 'Aparece na nota para o cliente; não muda valores.', 'Pagamento por PIX — chave CNPJ', 'Colocar aqui o valor do serviço ou as retenções: use os campos próprios.', 17),
 ('fiscal.nfse.emitir.codigo_tributacao', 'Código de tributação nacional', 'O código de 6 números do serviço na lista nacional da NFS-e. Vem do cadastro do serviço.', 'Diz à prefeitura qual serviço foi prestado e qual regra de ISS vale.', '140101', 'Usar o item da LC 116 com ponto ("14.01"): a nota nacional pede o código de 6 números.', 18),
 ('fiscal.nfse.emitir.municipio_prestacao', 'Município da execução', 'Digite e escolha a cidade onde o serviço foi feito, quando o ISS é devido no local da prestação.', 'Define a prefeitura que recebe o ISS e a alíquota usada.', 'Chapecó/SC', 'Escolher a cidade da sua empresa quando o serviço foi feito em outra.', 19),
 ('fiscal.nfse.emitir.iss_retido', 'ISS retido pelo tomador', 'Marque quando o cliente desconta e recolhe o ISS desta nota.', 'O ISS sai do valor a receber e a nota informa a retenção.', 'Marcado para serviço de obra em outro município', 'Marcar sem o cliente reter: você recebe a menos e o ISS fica sem recolher.', 20),
 ('fiscal.nfse.emitir.retencao_federal', 'Retenções federais', 'Marque o tributo que o cliente retém nesta nota e confira a alíquota. Vem do cadastro do serviço.', 'Os valores retidos vão na nota e saem do valor a receber.', 'IR 1,5%', 'Marcar retenção que o cliente não faz: o título a receber fica menor que o pago.', 21),
 ('fiscal.nfse.emitir.escopo_quantidade', 'Quantidade medida', 'Quanto deste item da obra esta nota mede. Não passe do que falta medir.', 'Abate do contratado da obra quando a prefeitura autorizar; nota cancelada estorna.', '12,5', 'Medir o total de uma vez numa nota parcial: o saldo da obra zera antes da hora.', 22),
 ('fiscal.nfse.emitir.financeiro_retencao', 'Retenção no título', 'O ISS retido pode ser ajustado; INSS, IR, PIS, COFINS e CSLL são os que foram na nota.', 'O título a receber nasce pelo valor líquido (nota menos retenções).', '30,00', 'Esperar que o título mude a nota: nota e título nunca divergem.', 23),
 ('fiscal.nfse.emitir.financeiro_deducoes', 'Deduções', 'Valores deduzidos do serviço, quando houver.', 'Reduzem o valor a receber do título.', '0,00', 'Repetir aqui uma retenção que já está nos campos acima.', 24),
 ('fiscal.nfse.emitir.financeiro_desconto', 'Desconto', 'Desconto dado ao cliente nesta nota, quando houver.', 'Reduz o valor a receber do título.', '50,00', 'Lançar o desconto aqui e também no valor da nota: desconta duas vezes.', 25),
 ('fiscal.nfse.emitir.financeiro_vencimento', '1º vencimento', 'A data do primeiro vencimento do título a receber.', 'Define quando o recebimento entra no fluxo de caixa.', '10/11/2026', 'Deixar em branco quando o cliente tem prazo: o título vence na data padrão.', 26)
) AS v(chave, rotulo, o_que, para_que, exemplo, erro, ordem)
ON CONFLICT (chave) DO NOTHING;
