-- Carga oficial LC116 → fiscal_codigo_catalogo (tipo='lc116'). Fronteira GE (fiscal).
--
-- Lista fornecida pelo CEO (rota "você manda, eu importo"): Anexo da LC 116/2003 com as
-- inclusões da LC 157/2016. Catálogo global, carga única. seed=false (dado OFICIAL).
-- capitulo = grupo_nome (agrupamento do item, ex.: "Serviços de informática e congêneres").
--
-- RD-51: importo EXATAMENTE a lista recebida, sem inventar ou completar subitens vetados.
-- Idempotente: ON CONFLICT (tipo,codigo) atualiza descrição/capítulo e reafirma oficial+ativo.

INSERT INTO public.fiscal_codigo_catalogo (tipo, codigo, descricao, capitulo, seed, ativo)
SELECT 'lc116', x->>'codigo', x->>'descricao', x->>'grupo_nome', false, true
FROM jsonb_array_elements($json$[
{"codigo":"1.01","descricao":"Análise e desenvolvimento de sistemas.","grupo_nome":"Serviços de informática e congêneres"},
{"codigo":"1.02","descricao":"Programação.","grupo_nome":"Serviços de informática e congêneres"},
{"codigo":"1.03","descricao":"Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres.","grupo_nome":"Serviços de informática e congêneres"},
{"codigo":"1.04","descricao":"Elaboração de programas de computadores, inclusive de jogos eletrônicos, independentemente da arquitetura construtiva da máquina em que o programa será executado, incluindo tablets, smartphones e congêneres.","grupo_nome":"Serviços de informática e congêneres"},
{"codigo":"1.05","descricao":"Licenciamento ou cessão de direito de uso de programas de computação.","grupo_nome":"Serviços de informática e congêneres"},
{"codigo":"1.06","descricao":"Assessoria e consultoria em informática.","grupo_nome":"Serviços de informática e congêneres"},
{"codigo":"1.07","descricao":"Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados.","grupo_nome":"Serviços de informática e congêneres"},
{"codigo":"1.08","descricao":"Planejamento, confecção, manutenção e atualização de páginas eletrônicas.","grupo_nome":"Serviços de informática e congêneres"},
{"codigo":"1.09","descricao":"Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto por meio da internet (streaming), respeitada a imunidade de livros, jornais e periódicos.","grupo_nome":"Serviços de informática e congêneres"},
{"codigo":"2.01","descricao":"Serviços de pesquisas e desenvolvimento de qualquer natureza.","grupo_nome":"Pesquisas e desenvolvimento"},
{"codigo":"3.02","descricao":"Cessão de direito de uso de marcas e de sinais de propaganda.","grupo_nome":"Locação, cessão de direito de uso e congêneres"},
{"codigo":"3.03","descricao":"Exploração de salões de festas, centro de convenções, escritórios virtuais, stands, quadras esportivas, estádios, ginásios, auditórios, casas de espetáculos, parques de diversões, canchas e congêneres, para realização de eventos ou negócios de qualquer natureza.","grupo_nome":"Locação, cessão de direito de uso e congêneres"},
{"codigo":"3.04","descricao":"Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia, rodovia, postes, cabos, dutos e condutos de qualquer natureza.","grupo_nome":"Locação, cessão de direito de uso e congêneres"},
{"codigo":"3.05","descricao":"Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.","grupo_nome":"Locação, cessão de direito de uso e congêneres"},
{"codigo":"4.01","descricao":"Medicina e biomedicina.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.02","descricao":"Análises clínicas, patologia, eletricidade médica, radioterapia, quimioterapia, ultra-sonografia, ressonância magnética, radiologia, tomografia e congêneres.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.03","descricao":"Hospitais, clínicas, laboratórios, sanatórios, manicômios, casas de saúde, prontos-socorros, ambulatórios e congêneres.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.04","descricao":"Instrumentação cirúrgica.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.05","descricao":"Acupuntura.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.06","descricao":"Enfermagem, inclusive serviços auxiliares.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.07","descricao":"Serviços farmacêuticos.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.08","descricao":"Terapia ocupacional, fisioterapia e fonoaudiologia.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.09","descricao":"Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.10","descricao":"Nutrição.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.11","descricao":"Obstetrícia.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.12","descricao":"Odontologia.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.13","descricao":"Ortóptica.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.14","descricao":"Próteses sob encomenda.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.15","descricao":"Psicanálise.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.16","descricao":"Psicologia.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.17","descricao":"Casas de repouso e de recuperação, creches, asilos e congêneres.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.18","descricao":"Inseminação artificial, fertilização in vitro e congêneres.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.19","descricao":"Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.20","descricao":"Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.21","descricao":"Unidade de atendimento, assistência ou tratamento móvel e congêneres.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.22","descricao":"Planos de medicina de grupo ou individual e convênios para prestação de assistência médica, hospitalar, odontológica e congêneres.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"4.23","descricao":"Outros planos de saúde que se cumpram através de serviços de terceiros contratados, credenciados, cooperados ou apenas pagos pelo operador do plano mediante indicação do beneficiário.","grupo_nome":"Saúde, assistência médica e congêneres"},
{"codigo":"5.01","descricao":"Medicina veterinária e zootecnia.","grupo_nome":"Medicina e assistência veterinária"},
{"codigo":"5.02","descricao":"Hospitais, clínicas, ambulatórios, prontos-socorros e congêneres, na área veterinária.","grupo_nome":"Medicina e assistência veterinária"},
{"codigo":"5.03","descricao":"Laboratórios de análise na área veterinária.","grupo_nome":"Medicina e assistência veterinária"},
{"codigo":"5.04","descricao":"Inseminação artificial, fertilização in vitro e congêneres.","grupo_nome":"Medicina e assistência veterinária"},
{"codigo":"5.05","descricao":"Bancos de sangue e de órgãos e congêneres.","grupo_nome":"Medicina e assistência veterinária"},
{"codigo":"5.06","descricao":"Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie.","grupo_nome":"Medicina e assistência veterinária"},
{"codigo":"5.07","descricao":"Unidade de atendimento, assistência ou tratamento móvel e congêneres.","grupo_nome":"Medicina e assistência veterinária"},
{"codigo":"5.08","descricao":"Guarda, tratamento, amestramento, embelezamento, alojamento e congêneres.","grupo_nome":"Medicina e assistência veterinária"},
{"codigo":"5.09","descricao":"Planos de atendimento e assistência médico-veterinária.","grupo_nome":"Medicina e assistência veterinária"},
{"codigo":"6.01","descricao":"Barbearia, cabeleireiros, manicuros, pedicuros e congêneres.","grupo_nome":"Cuidados pessoais, estética, atividades físicas"},
{"codigo":"6.02","descricao":"Esteticistas, tratamento de pele, depilação e congêneres.","grupo_nome":"Cuidados pessoais, estética, atividades físicas"},
{"codigo":"6.03","descricao":"Banhos, duchas, sauna, massagens e congêneres.","grupo_nome":"Cuidados pessoais, estética, atividades físicas"},
{"codigo":"6.04","descricao":"Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas.","grupo_nome":"Cuidados pessoais, estética, atividades físicas"},
{"codigo":"6.05","descricao":"Centros de emagrecimento, spa e congêneres.","grupo_nome":"Cuidados pessoais, estética, atividades físicas"},
{"codigo":"6.06","descricao":"Aplicação de tatuagens, piercings e congêneres.","grupo_nome":"Cuidados pessoais, estética, atividades físicas"},
{"codigo":"7.01","descricao":"Engenharia, agronomia, agrimensura, arquitetura, geologia, urbanismo, paisagismo e congêneres.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.02","descricao":"Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes, inclusive sondagem, perfuração de poços, escavação, drenagem e irrigação, terraplanagem, pavimentação, concretagem e a instalação e montagem de produtos, peças e equipamentos (exceto fornecimento de mercadorias produzidas fora do local, sujeito ao ICMS).","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.03","descricao":"Elaboração de planos diretores, estudos de viabilidade, estudos organizacionais e outros, relacionados com obras e serviços de engenharia; elaboração de anteprojetos, projetos básicos e projetos executivos para trabalhos de engenharia.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.04","descricao":"Demolição.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.05","descricao":"Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres (exceto fornecimento de mercadorias produzidas fora do local, sujeito ao ICMS).","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.06","descricao":"Colocação e instalação de tapetes, carpetes, assoalhos, cortinas, revestimentos de parede, vidros, divisórias, placas de gesso e congêneres, com material fornecido pelo tomador do serviço.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.07","descricao":"Recuperação, raspagem, polimento e lustração de pisos e congêneres.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.08","descricao":"Calafetação.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.09","descricao":"Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.10","descricao":"Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.11","descricao":"Decoração e jardinagem, inclusive corte e poda de árvores.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.12","descricao":"Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.13","descricao":"Dedetização, desinfecção, desinsetização, imunização, higienização, desratização, pulverização e congêneres.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.16","descricao":"Florestamento, reflorestamento, semeadura, adubação, reparação de solo, plantio, silagem, colheita, corte e descascamento de árvores, silvicultura, exploração florestal e dos serviços congêneres indissociáveis da formação, manutenção e colheita de florestas, para quaisquer fins e por quaisquer meios.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.17","descricao":"Escoramento, contenção de encostas e serviços congêneres.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.18","descricao":"Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.19","descricao":"Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.20","descricao":"Aerofotogrametria (inclusive interpretação), cartografia, mapeamento, levantamentos topográficos, batimétricos, geográficos, geodésicos, geológicos, geofísicos e congêneres.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.21","descricao":"Pesquisa, perfuração, cimentação, mergulho, perfilagem, concretação, testemunhagem, pescaria, estimulação e outros serviços relacionados com a exploração e explotação de petróleo, gás natural e de outros recursos minerais.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"7.22","descricao":"Nucleação e bombardeamento de nuvens e congêneres.","grupo_nome":"Engenharia, arquitetura, construção civil, manutenção, limpeza, meio ambiente, saneamento"},
{"codigo":"8.01","descricao":"Ensino regular pré-escolar, fundamental, médio e superior.","grupo_nome":"Educação, ensino, treinamento"},
{"codigo":"8.02","descricao":"Instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de qualquer natureza.","grupo_nome":"Educação, ensino, treinamento"},
{"codigo":"9.01","descricao":"Hospedagem de qualquer natureza em hotéis, apart-service condominiais, flat, apart-hotéis, hotéis residência, residence-service, suite service, hotelaria marítima, motéis, pensões e congêneres; ocupação por temporada com fornecimento de serviço.","grupo_nome":"Hospedagem, turismo, viagens"},
{"codigo":"9.02","descricao":"Agenciamento, organização, promoção, intermediação e execução de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres.","grupo_nome":"Hospedagem, turismo, viagens"},
{"codigo":"9.03","descricao":"Guias de turismo.","grupo_nome":"Hospedagem, turismo, viagens"},
{"codigo":"10.01","descricao":"Agenciamento, corretagem ou intermediação de câmbio, de seguros, de cartões de crédito, de planos de saúde e de planos de previdência privada.","grupo_nome":"Intermediação e congêneres"},
{"codigo":"10.02","descricao":"Agenciamento, corretagem ou intermediação de títulos em geral, valores mobiliários e contratos quaisquer.","grupo_nome":"Intermediação e congêneres"},
{"codigo":"10.03","descricao":"Agenciamento, corretagem ou intermediação de direitos de propriedade industrial, artística ou literária.","grupo_nome":"Intermediação e congêneres"},
{"codigo":"10.04","descricao":"Agenciamento, corretagem ou intermediação de contratos de arrendamento mercantil (leasing), de franquia (franchising) e de faturização (factoring).","grupo_nome":"Intermediação e congêneres"},
{"codigo":"10.05","descricao":"Agenciamento, corretagem ou intermediação de bens móveis ou imóveis, não abrangidos em outros itens ou subitens, inclusive os realizados no âmbito de Bolsas de Mercadorias e Futuros.","grupo_nome":"Intermediação e congêneres"},
{"codigo":"10.06","descricao":"Agenciamento marítimo.","grupo_nome":"Intermediação e congêneres"},
{"codigo":"10.07","descricao":"Agenciamento de notícias.","grupo_nome":"Intermediação e congêneres"},
{"codigo":"10.08","descricao":"Agenciamento de publicidade e propaganda, inclusive o agenciamento de veiculação por quaisquer meios.","grupo_nome":"Intermediação e congêneres"},
{"codigo":"10.09","descricao":"Representação de qualquer natureza, inclusive comercial.","grupo_nome":"Intermediação e congêneres"},
{"codigo":"10.10","descricao":"Distribuição de bens de terceiros.","grupo_nome":"Intermediação e congêneres"},
{"codigo":"11.01","descricao":"Guarda e estacionamento de veículos terrestres automotores, de aeronaves e de embarcações.","grupo_nome":"Guarda, estacionamento, armazenamento, vigilância"},
{"codigo":"11.02","descricao":"Vigilância, segurança ou monitoramento de bens, pessoas e semoventes.","grupo_nome":"Guarda, estacionamento, armazenamento, vigilância"},
{"codigo":"11.03","descricao":"Escolta, inclusive de veículos e cargas.","grupo_nome":"Guarda, estacionamento, armazenamento, vigilância"},
{"codigo":"11.04","descricao":"Armazenamento, depósito, carga, descarga, arrumação e guarda de bens de qualquer espécie.","grupo_nome":"Guarda, estacionamento, armazenamento, vigilância"},
{"codigo":"11.05","descricao":"Serviços relacionados ao monitoramento e rastreamento a distância, em qualquer via ou local, de veículos, cargas, pessoas e semoventes em circulação ou movimento.","grupo_nome":"Guarda, estacionamento, armazenamento, vigilância"},
{"codigo":"12.01","descricao":"Espetáculos teatrais.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.02","descricao":"Exibições cinematográficas.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.03","descricao":"Espetáculos circenses.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.04","descricao":"Programas de auditório.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.05","descricao":"Parques de diversões, centros de lazer e congêneres.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.06","descricao":"Boates, taxi-dancing e congêneres.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.07","descricao":"Shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.08","descricao":"Feiras, exposições, congressos e congêneres.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.09","descricao":"Bilhares, boliches e diversões eletrônicas ou não.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.10","descricao":"Corridas e competições de animais.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.11","descricao":"Competições esportivas ou de destreza física ou intelectual, com ou sem a participação do espectador.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.12","descricao":"Execução de música.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.13","descricao":"Produção, mediante ou sem encomenda prévia, de eventos, espetáculos, entrevistas, shows, ballet, danças, desfiles, bailes, teatros, óperas, concertos, recitais, festivais e congêneres.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.14","descricao":"Fornecimento de música para ambientes fechados ou não, mediante transmissão por qualquer processo.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.15","descricao":"Desfiles de blocos carnavalescos ou folclóricos, trios elétricos e congêneres.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.16","descricao":"Exibição de filmes, entrevistas, musicais, espetáculos, shows, concertos, desfiles, óperas, competições esportivas, de destreza intelectual ou congêneres.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"12.17","descricao":"Recreação e animação, inclusive em festas e eventos de qualquer natureza.","grupo_nome":"Diversões, lazer, entretenimento"},
{"codigo":"13.02","descricao":"Fonografia ou gravação de sons, inclusive trucagem, dublagem, mixagem e congêneres.","grupo_nome":"Fonografia, fotografia, cinematografia, reprografia"},
{"codigo":"13.03","descricao":"Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres.","grupo_nome":"Fonografia, fotografia, cinematografia, reprografia"},
{"codigo":"13.04","descricao":"Reprografia, microfilmagem e digitalização.","grupo_nome":"Fonografia, fotografia, cinematografia, reprografia"},
{"codigo":"13.05","descricao":"Composição gráfica, inclusive confecção de impressos gráficos, fotocomposição, clicheria, zincografia, litografia e fotolitografia (exceto se destinados a posterior comercialização/industrialização, quando sujeitos ao ICMS).","grupo_nome":"Fonografia, fotografia, cinematografia, reprografia"},
{"codigo":"14.01","descricao":"Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, blindagem, manutenção e conservação de máquinas, veículos, aparelhos, equipamentos, motores, elevadores ou de qualquer objeto (exceto peças e partes empregadas, sujeitas ao ICMS).","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.02","descricao":"Assistência técnica.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.03","descricao":"Recondicionamento de motores (exceto peças e partes empregadas, sujeitas ao ICMS).","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.04","descricao":"Recauchutagem ou regeneração de pneus.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.05","descricao":"Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento, galvanoplastia, anodização, corte, recorte, plastificação, costura, acabamento, polimento e congêneres de objetos quaisquer.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.06","descricao":"Instalação e montagem de aparelhos, máquinas e equipamentos, inclusive montagem industrial, prestados ao usuário final, exclusivamente com material por ele fornecido.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.07","descricao":"Colocação de molduras e congêneres.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.08","descricao":"Encadernação, gravação e douração de livros, revistas e congêneres.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.09","descricao":"Alfaiataria e costura, quando o material for fornecido pelo usuário final, exceto aviamento.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.10","descricao":"Tinturaria e lavanderia.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.11","descricao":"Tapeçaria e reforma de estofamentos em geral.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.12","descricao":"Funilaria e lanternagem.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.13","descricao":"Carpintaria e serralheria.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"14.14","descricao":"Guincho intramunicipal, guindaste e içamento.","grupo_nome":"Serviços relativos a bens de terceiros"},
{"codigo":"15.01","descricao":"Administração de fundos quaisquer, de consórcio, de cartão de crédito ou débito e congêneres, de carteira de clientes, de cheques pré-datados e congêneres.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.02","descricao":"Abertura de contas em geral, inclusive conta-corrente, conta de investimentos e aplicação e caderneta de poupança, no País e no exterior, bem como a manutenção das referidas contas ativas e inativas.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.03","descricao":"Locação e manutenção de cofres particulares, de terminais eletrônicos, de terminais de atendimento e de bens e equipamentos em geral.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.04","descricao":"Fornecimento ou emissão de atestados em geral, inclusive atestado de idoneidade, atestado de capacidade financeira e congêneres.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.05","descricao":"Cadastro, elaboração de ficha cadastral, renovação cadastral e congêneres, inclusão ou exclusão no CCF ou em quaisquer outros bancos cadastrais.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.06","descricao":"Emissão, reemissão e fornecimento de avisos, comprovantes e documentos em geral; abono de firmas; coleta e entrega de documentos, bens e valores; licenciamento eletrônico de veículos; transferência de veículos; agenciamento fiduciário ou depositário; devolução de bens em custódia.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.07","descricao":"Acesso, movimentação, atendimento e consulta a contas em geral, por qualquer meio ou processo, inclusive por telefone, fac-símile, internet e telex; fornecimento de saldo, extrato e demais informações relativas a contas em geral.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.08","descricao":"Emissão, reemissão, alteração, cessão, substituição, cancelamento e registro de contrato de crédito; estudo, análise e avaliação de operações de crédito; emissão de aval, fiança e congêneres; serviços relativos a abertura de crédito.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.09","descricao":"Arrendamento mercantil (leasing) de quaisquer bens, inclusive cessão de direitos e obrigações, substituição de garantia, alteração, cancelamento e registro de contrato, e demais serviços relacionados.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.10","descricao":"Serviços relacionados a cobranças, recebimentos ou pagamentos em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros; emissão de carnês, fichas de compensação, impressos e documentos em geral.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.11","descricao":"Devolução de títulos, protesto de títulos, sustação de protesto, manutenção de títulos, reapresentação de títulos, e demais serviços a eles relacionados.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.12","descricao":"Custódia em geral, inclusive de títulos e valores mobiliários.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.13","descricao":"Serviços relacionados a operações de câmbio em geral; emissão de registro de exportação ou de crédito; cobrança ou depósito no exterior; cheques de viagem; carta de crédito de importação/exportação e garantias recebidas.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.14","descricao":"Fornecimento, emissão, reemissão, renovação e manutenção de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.15","descricao":"Compensação de cheques e títulos quaisquer; serviços relacionados a depósito, inclusive depósito identificado, a saque de contas quaisquer, inclusive em terminais eletrônicos e de atendimento.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.16","descricao":"Emissão, reemissão, liquidação, alteração, cancelamento e baixa de ordens de pagamento, ordens de crédito e similares; serviços relacionados à transferência de valores, dados, fundos, pagamentos e similares, inclusive entre contas em geral.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.17","descricao":"Emissão, fornecimento, devolução, sustação, cancelamento e oposição de cheques quaisquer, avulso ou por talão.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"15.18","descricao":"Serviços relacionados a crédito imobiliário, avaliação e vistoria de imóvel ou obra, análise técnica e jurídica, emissão/alteração/transferência e renegociação de contrato, termo de quitação e demais serviços relacionados a crédito imobiliário.","grupo_nome":"Setor bancário ou financeiro"},
{"codigo":"16.01","descricao":"Serviços de transporte coletivo municipal rodoviário, metroviário, ferroviário e aquaviário de passageiros.","grupo_nome":"Transporte de natureza municipal"},
{"codigo":"16.02","descricao":"Outros serviços de transporte de natureza municipal.","grupo_nome":"Transporte de natureza municipal"},
{"codigo":"17.01","descricao":"Assessoria ou consultoria de qualquer natureza, não contida em outros itens desta lista; análise, exame, pesquisa, coleta, compilação e fornecimento de dados e informações de qualquer natureza, inclusive cadastro e similares.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.02","descricao":"Datilografia, digitação, estenografia, expediente, secretaria em geral, resposta audível, redação, edição, interpretação, revisão, tradução, apoio e infra-estrutura administrativa e congêneres.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.03","descricao":"Planejamento, coordenação, programação ou organização técnica, financeira ou administrativa.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.04","descricao":"Recrutamento, agenciamento, seleção e colocação de mão-de-obra.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.05","descricao":"Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.06","descricao":"Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas ou sistemas de publicidade, elaboração de desenhos, textos e demais materiais publicitários.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.08","descricao":"Franquia (franchising).","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.09","descricao":"Perícias, laudos, exames técnicos e análises técnicas.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.10","descricao":"Planejamento, organização e administração de feiras, exposições, congressos e congêneres.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.11","descricao":"Organização de festas e recepções; bufê (exceto o fornecimento de alimentação e bebidas, sujeito ao ICMS).","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.12","descricao":"Administração em geral, inclusive de bens e negócios de terceiros.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.13","descricao":"Leilão e congêneres.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.14","descricao":"Advocacia.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.15","descricao":"Arbitragem de qualquer espécie, inclusive jurídica.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.16","descricao":"Auditoria.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.17","descricao":"Análise de Organização e Métodos.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.18","descricao":"Atuária e cálculos técnicos de qualquer natureza.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.19","descricao":"Contabilidade, inclusive serviços técnicos e auxiliares.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.20","descricao":"Consultoria e assessoria econômica ou financeira.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.21","descricao":"Estatística.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.22","descricao":"Cobrança em geral.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.23","descricao":"Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção, gerenciamento de informações, administração de contas a receber ou a pagar e em geral, relacionados a operações de faturização (factoring).","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.24","descricao":"Apresentação de palestras, conferências, seminários e congêneres.","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"17.25","descricao":"Inserção de textos, desenhos e outros materiais de propaganda e publicidade, em qualquer meio (exceto em livros, jornais, periódicos e radiodifusão de recepção livre e gratuita).","grupo_nome":"Apoio técnico, administrativo, jurídico, contábil, comercial"},
{"codigo":"18.01","descricao":"Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos para cobertura de contratos de seguros; prevenção e gerência de riscos seguráveis e congêneres.","grupo_nome":"Regulação de sinistros de seguros"},
{"codigo":"19.01","descricao":"Serviços de distribuição e venda de bilhetes e demais produtos de loteria, bingos, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres.","grupo_nome":"Distribuição e venda de bilhetes de loteria"},
{"codigo":"20.01","descricao":"Serviços portuários, ferroportuários, utilização de porto, movimentação de passageiros, reboque de embarcações, atracação, praticagem, capatazia, armazenagem, movimentação de mercadorias, apoio marítimo, estiva, conferência, logística e congêneres.","grupo_nome":"Portuários, aeroportuários, terminais"},
{"codigo":"20.02","descricao":"Serviços aeroportuários, utilização de aeroporto, movimentação de passageiros, armazenagem, capatazia, movimentação de aeronaves, apoio aeroportuário, movimentação de mercadorias, logística e congêneres.","grupo_nome":"Portuários, aeroportuários, terminais"},
{"codigo":"20.03","descricao":"Serviços de terminais rodoviários, ferroviários, metroviários, movimentação de passageiros, mercadorias, inclusive suas operações, logística e congêneres.","grupo_nome":"Portuários, aeroportuários, terminais"},
{"codigo":"21.01","descricao":"Serviços de registros públicos, cartorários e notariais.","grupo_nome":"Registros públicos, cartorários e notariais"},
{"codigo":"22.01","descricao":"Serviços de exploração de rodovia mediante cobrança de preço ou pedágio dos usuários, envolvendo conservação, manutenção, melhoramentos, operação, monitoração, assistência aos usuários e outros serviços definidos em contratos ou concessão.","grupo_nome":"Exploração de rodovia"},
{"codigo":"23.01","descricao":"Serviços de programação e comunicação visual, desenho industrial e congêneres.","grupo_nome":"Programação e comunicação visual, desenho industrial"},
{"codigo":"24.01","descricao":"Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners, adesivos e congêneres.","grupo_nome":"Chaveiros, carimbos, placas, sinalização"},
{"codigo":"25.01","descricao":"Funerais, inclusive fornecimento de caixão, urna ou esquifes; aluguel de capela; transporte do corpo cadavérico; fornecimento de flores, coroas e outros paramentos; desembaraço de certidão de óbito; embalsamento, embelezamento, conservação ou restauração de cadáveres.","grupo_nome":"Serviços funerários"},
{"codigo":"25.02","descricao":"Translado intramunicipal e cremação de corpos e partes de corpos cadavéricos.","grupo_nome":"Serviços funerários"},
{"codigo":"25.03","descricao":"Planos ou convênio funerários.","grupo_nome":"Serviços funerários"},
{"codigo":"25.04","descricao":"Manutenção e conservação de jazigos e cemitérios.","grupo_nome":"Serviços funerários"},
{"codigo":"25.05","descricao":"Cessão de uso de espaços em cemitérios para sepultamento.","grupo_nome":"Serviços funerários"},
{"codigo":"26.01","descricao":"Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios e suas agências franqueadas; courrier e congêneres.","grupo_nome":"Coleta, remessa ou entrega de correspondências"},
{"codigo":"27.01","descricao":"Serviços de assistência social.","grupo_nome":"Assistência social"},
{"codigo":"28.01","descricao":"Serviços de avaliação de bens e serviços de qualquer natureza.","grupo_nome":"Avaliação de bens"},
{"codigo":"29.01","descricao":"Serviços de biblioteconomia.","grupo_nome":"Biblioteconomia"},
{"codigo":"30.01","descricao":"Serviços de biologia, biotecnologia e química.","grupo_nome":"Biologia, biotecnologia e química"},
{"codigo":"31.01","descricao":"Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres.","grupo_nome":"Serviços técnicos em edificações, eletrônica, mecânica"},
{"codigo":"32.01","descricao":"Serviços de desenhos técnicos.","grupo_nome":"Desenhos técnicos"},
{"codigo":"33.01","descricao":"Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres.","grupo_nome":"Desembaraço aduaneiro, despachantes"},
{"codigo":"34.01","descricao":"Serviços de investigações particulares, detetives e congêneres.","grupo_nome":"Investigações particulares, detetives"},
{"codigo":"35.01","descricao":"Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas.","grupo_nome":"Reportagem, assessoria de imprensa, jornalismo"},
{"codigo":"36.01","descricao":"Serviços de meteorologia.","grupo_nome":"Meteorologia"},
{"codigo":"37.01","descricao":"Serviços de artistas, atletas, modelos e manequins.","grupo_nome":"Artistas, atletas, modelos e manequins"},
{"codigo":"38.01","descricao":"Serviços de museologia.","grupo_nome":"Museologia"},
{"codigo":"39.01","descricao":"Serviços de ourivesaria e lapidação (quando o material for fornecido pelo tomador do serviço).","grupo_nome":"Ourivesaria e lapidação"},
{"codigo":"40.01","descricao":"Obras de arte sob encomenda.","grupo_nome":"Obras de arte sob encomenda"}
]$json$::jsonb) x
ON CONFLICT (tipo, codigo) DO UPDATE
  SET descricao = EXCLUDED.descricao,
      capitulo  = EXCLUDED.capitulo,
      seed      = false,
      ativo     = true;
