-- Produtividade Onda 2 (tela): "?" de ajuda dos campos de produto e estrutura (chaves prod.produto.* e prod.estrutura.*).
-- "Para que serve no cálculo" escrito a partir do que as funções FAZEM hoje (RD-51/72): fn_prod_estrutura_salvar/listar/colar só
-- cadastram e validam (sem ciclo; soma > 100% só avisa; rendimento NULL = a definir, 0 é recusado). Nenhum indicador lê a estrutura
-- ainda — o cálculo de rendimento real × padrão e o balanço de massa chegam na onda de medição.
-- Aditiva: só INSERT de textos (ON CONFLICT DO NOTHING). Sem dado de cliente.

INSERT INTO public.erp_ajuda_campo (chave, grupo, rotulo, o_que_preencher, para_que_serve, exemplo, erro_comum, ordem, rota, vertical, status)
SELECT v.chave, 'Produto e estrutura', v.rotulo, v.o_que, v.para_que, v.exemplo, v.erro, v.ordem, '/dashboard/produtividade', 'industria', 'publicado'
FROM (VALUES
 ('prod.produto.acabado', 'Produto acabado', 'O produto que gera faturamento. Busque por código ou nome; se a empresa tem fonte de produção ligada, a busca olha também nela e cria o produto ao escolher; sem fonte, cadastre à mão.', 'Define de onde a árvore parte. Hoje só organiza o cadastro: o kg/homem-hora ainda não lê a árvore.', 'o produto que você fatura', 'Buscar pelo nome da fonte e não achar: a fonte só lista o que já teve produção registrada.', 50),
 ('prod.produto.codigo', 'Código do produto', 'O código que a empresa usa para o produto. Único por planta.', 'É a chave para colar listas e para ligar o produto às fontes. Não entra em conta.', '47', 'Repetir um código já cadastrado: o sistema recusa (arquivado é reaproveitado).', 51),
 ('prod.produto.nome', 'Nome do produto', 'Como a empresa chama o produto.', 'Só identifica o produto na árvore e nas listas.', 'Coxão mole resfriado', 'Deixar vazio: não salva.', 52),
 ('prod.produto.papel', 'Papel do produto', 'Acabado (o que se fatura), intermediário (sai de uma etapa e entra na seguinte), origem (a matéria-prima) ou subproduto.', 'Só classifica o cadastro e filtra listas; a árvore nasce das ligações, não do papel.', 'intermediário', 'Achar que o papel liga os produtos: quem liga é a estrutura (origem → saída).', 53),
 ('prod.produto.unidade', 'Unidade do produto', 'A unidade em que o produto é contado (kg, cabeça, m³, peça…), da lista de unidades da planta.', 'Fica no cadastro do produto. Nenhuma conta converte unidade ainda.', 'kg', 'Esperar conversão automática entre unidades: ainda não há.', 54),
 ('prod.estrutura.origem', 'Produto de origem', 'O produto de que este vem (na desmontagem: o que entra na etapa).', 'Cada ligação origem → saída é uma linha da estrutura. O sistema recusa ligação que feche um ciclo.', 'a peça inteira que será desossada', 'Ligar um produto a ele mesmo ou a um descendente: recusado ("ciclo").', 55),
 ('prod.estrutura.saida', 'Produto gerado (saída)', 'Um produto que sai da origem, além do que já está na árvore (coproduto ou subproduto).', 'Cadastra mais uma linha origem → saída. As saídas de uma origem são somadas só para avisar quando passam de 100%.', 'osso (subproduto)', 'Cadastrar a mesma saída duas vezes na mesma etapa: recusado ("já existe").', 56),
 ('prod.estrutura.tipo_saida', 'Tipo da saída', 'Principal, coproduto ou subproduto.', 'Só classifica a saída; não muda nenhuma conta ainda.', 'coproduto', 'Marcar tudo como principal: perde-se a diferença entre o que se fatura e o que sobra.', 57),
 ('prod.estrutura.rendimento', 'Rendimento padrão %', 'Quanto da origem vira esta saída, em %. Em branco = "a definir" — nunca zero.', 'É o padrão contra o qual o rendimento real será comparado na onda de medição. Hoje só é guardado; soma das saídas acima de 100% gera aviso (não bloqueia).', '12,5', 'Digitar 0 para "não sei": zero é recusado — deixe em branco.', 58),
 ('prod.estrutura.etapa', 'Etapa', 'Em qual fluxo (etapa) esta transformação acontece. Opcional.', 'Liga a ligação ao fluxo; é o que a faixa "Pronto para medir" conta como saída da etapa.', 'Desossa de Bola', 'Esquecer a etapa: a faixa avisa que o fluxo não tem saídas.', 59),
 ('prod.estrutura.status', 'Status da ligação', 'Rascunho (a validar) ou validado.', 'Marca se alguém da empresa confirmou o padrão. Sugestões e listas coladas entram como rascunho. Ainda não muda conta.', 'validado', 'Validar sem conferir o rendimento com a produção.', 60),
 ('prod.estrutura.colar', 'Colar lista', 'Cole uma linha por ligação: origem;produto;tipo_saida;rendimento_pct;etapa (códigos dos produtos já cadastrados). Mostra a prévia, avisa o que não casou e grava como rascunho.', 'Atalho para cadastrar a estrutura de uma vez. Nada é gravado na prévia; linhas inválidas ficam de fora.', '47;46;coproduto;12,5;Desossa', 'Usar nome em vez de código: o código precisa existir em Produtos.', 61),
 ('prod.fluxo.origem', 'Origem do fluxo', 'O produto que entra na etapa deste fluxo.', 'Guarda a entrada da etapa e é uma das condições da faixa "Pronto para medir" deste fluxo.', 'a peça que entra na desossa', 'Deixar vazio: o fluxo aparece como não pronto.', 62)
) AS v(chave, rotulo, o_que, para_que, exemplo, erro, ordem)
WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'erp_ajuda_campo')
ON CONFLICT (chave) DO NOTHING;
