-- P&M · apontamento de horas em 1 toque (onda 2 da P&M da Pdois, mapeamento do SIGA, Parte S, atrito 18) — o "?" dos
-- campos e ações da tela Apontamento de horas e do ▶ em Meus trabalhos (RD-95). Aditiva: só texto de ajuda novo; sem dado de cliente.
INSERT INTO public.erp_ajuda_campo (chave, grupo, rotulo, o_que_preencher, para_que_serve, exemplo, erro_comum, ordem, rota, vertical, status)
SELECT v.chave, v.grupo, v.rotulo, v.o_que, v.para_que, v.exemplo, v.erro, v.ordem, v.rota, 'pm', 'publicado'
FROM (VALUES
 ('pm.apontamento.job', 'Apontamento', 'Job', 'Escolha o job em que você trabalhou. Vindo do aviso "Lançar horas" ou "apontar", o job já chega escolhido.', 'As horas entram no custo desse job: horas × custo/hora da pessoa, e daí na margem por job, cliente e fee.', 'JOB-0142 · Post de lançamento do cliente', 'Apontar no job errado: a margem de um job fica pior e a do outro melhor do que a real.', 1, '/dashboard/pm/apontamento-horas'),
 ('pm.apontamento.responsavel', 'Apontamento', 'Responsável', 'Quem fez o trabalho, para usar o custo/hora dessa pessoa. Só quem vê salário enxerga os valores.', 'Define o custo/hora usado no custo do job. Sem custo/hora, as horas entram e a Margem avisa que falta o custo.', 'Ana Paula · R$ 37,50/h', 'Deixar em branco quando quem vê salário está apontando por outra pessoa: as horas entram sem custo.', 2, '/dashboard/pm/apontamento-horas'),
 ('pm.apontamento.atalho', 'Apontamento', 'Apontar em 1 toque', 'Com o job escolhido, toque em +15 min, +30 min, +1 h ou +2 h. Grava na hora, com a data de hoje.', 'É o jeito mais rápido de não deixar hora sem apontar: cada toque vira uma linha de horas do job.', 'Revisou a arte por meia hora: toque em +30 min.', 'Tocar duas vezes sem querer: a hora entra duas vezes. Confira a lista logo abaixo.', 3, '/dashboard/pm/apontamento-horas'),
 ('pm.apontamento.cronometro', 'Apontamento', 'Cronômetro', 'Toque em Iniciar quando começar o trabalho e em Parar quando terminar. O ▶ dos cartões da Pauta, do Meu dia e de Meus trabalhos faz o mesmo.', 'Grava as horas exatas do período no job escolhido, sem precisar lembrar depois.', 'Iniciou às 14h, parou às 15h20: entram 1,33 h.', 'Esquecer o cronômetro ligado no fim do dia: as horas ficam maiores do que as trabalhadas.', 4, '/dashboard/pm/apontamento-horas'),
 ('pm.apontamento.horas', 'Apontamento', 'Horas (manual)', 'As horas trabalhadas, em número decimal, quando nenhum atalho serve. Depois toque em + Manual.', 'Entra no custo do job do mesmo jeito que o cronômetro.', '1 h e 45 min = 1,75', 'Escrever 1,45 querendo dizer 1 h 45 min: entram 1 h 27 min.', 5, '/dashboard/pm/apontamento-horas'),
 ('pm.apontamento.descricao', 'Apontamento', 'Descrição', 'O que foi feito nessas horas, em poucas palavras (opcional).', 'Ajuda o gestor a entender as horas do job e a explicar o custo ao cliente.', 'Ajuste de cores após o retorno do cliente', 'Escrever só "trabalho": não ajuda ninguém a entender depois.', 6, '/dashboard/pm/apontamento-horas'),
 ('pm.meus_trabalhos.apontar', 'Meus trabalhos', '▶ Apontar horas', 'Toque no ▶ do job para iniciar o cronômetro nele; toque de novo (■) para parar e gravar. Iniciar em outro job para o anterior sozinho.', 'Aponta as horas na sua própria fila, sem abrir o job nem outra tela. As horas entram no custo e na margem do job.', 'Começou o JOB-0142: toque no ▶; foi para o JOB-0150: toque no ▶ dele, o primeiro para sozinho.', 'Deixar o ▶ ligado ao sair: as horas continuam contando até você parar.', 2, '/dashboard/pm/meus-trabalhos')
) AS v(chave, grupo, rotulo, o_que, para_que, exemplo, erro, ordem, rota)
WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'erp_ajuda_campo')
ON CONFLICT (chave) DO NOTHING;
