-- Produtividade › Cadastro por fluxo: "?" de ajuda em todo campo e cabeçalho (CEO 07/10, caixa 3f7d187f).
-- Textos escritos a partir da definição VIVA de fn_prod_indicadores e fn_prod_prontidao (RD-51/RD-72), sem dedução:
--  · fn_prod_indicadores calcula kg/homem-hora por setor FIXO (DESOSSA e ABATE) = produção do ATAK (QTDE_KG) ÷ horas do ponto
--    (ind_ponto_dia.worked_seconds, por departamento); só entra o dia com ≥5 pessoas e ≥4 h por pessoa. NÃO lê prod_posto,
--    prod_fluxo, capacidade, cargo, pessoas do quadro nem salário.
--  · fn_prod_prontidao só confere: ≥1 posto ativo, ≥1 quadro de turno aberto (prod_posto_turno sem vigencia_fim) e ≥1 setor
--    vinculado a uma base (ponto/produção).
-- Aditiva: só INSERT de textos (ON CONFLICT DO NOTHING). Sem dado de cliente.

INSERT INTO public.erp_ajuda_campo (chave, grupo, rotulo, o_que_preencher, para_que_serve, exemplo, erro_comum, ordem, rota, vertical, status)
SELECT v.chave, 'Cadastro por fluxo', v.rotulo, v.o_que, v.para_que, v.exemplo, v.erro, v.ordem, '/dashboard/produtividade', 'industria', 'publicado'
FROM (VALUES
 ('prod.fluxo.nome', 'Nome do fluxo', 'O contexto de produção que você quer medir, em poucas palavras. Clique no nome para trocar.', 'É o título do cadastro: agrupa os postos e aparece na lista de fluxos. O indicador kg/homem-hora de hoje não lê o nome do fluxo — ele vem do ponto e da produção do ATAK por setor.', 'Desossa de Bola', 'Dois fluxos com o mesmo nome na mesma planta: o sistema recusa e avisa.', 10),
 ('prod.fluxo.setor', 'Setor do fluxo', 'Escolha o setor onde este fluxo acontece (os setores são criados em ⚙ Cadastros).', 'Os postos listados são os do setor do fluxo. Hoje o indicador kg/homem-hora é calculado para os setores DESOSSA e ABATE, lendo o ponto (departamento) e a produção do ATAK — não o setor cadastrado aqui. O setor também precisa estar vinculado a uma base de ponto/produção para a faixa "Pronto para medir" ficar verde.', 'Desossa', 'Trocar o setor depois de cadastrar postos: a tela passa a mostrar os postos do novo setor (os do setor antigo não somem, só deixam de aparecer neste fluxo).', 11),
 ('prod.fluxo.unidade_entrada', 'Entra (unidade)', 'A unidade do que entra no fluxo (KG, cabeça…). Escolha na lista; novas unidades em ⚙ Cadastros.', 'Fica registrada como contexto do fluxo. O kg/homem-hora de hoje usa sempre QTDE_KG do ATAK dividido pelas horas do ponto; esta unidade ainda não muda a conta.', 'KG', 'Escolher uma unidade diferente da que o ATAK entrega e achar que o indicador converte: não converte (cabeças→kg não tem conversão cadastrada).', 12),
 ('prod.posto.numero', 'Nº do posto', 'O número do posto na linha (1, 2, 3… ou um código seu). Único dentro do setor.', 'Define a ordem de apresentação e identifica o posto. Não entra em nenhuma conta de indicador.', '3', 'Repetir um número que já existe no setor: o sistema recusa ("Já existe um posto com o número…").', 20),
 ('prod.posto.atividade', 'Atividade', 'O que o posto faz, em linguagem de chão de fábrica. Obrigatória.', 'Identifica o posto. Não entra em conta de indicador; serve para quem lê o cadastro e, depois, para ligar cada posto à produção.', 'Refile de alcatra', 'Deixar vazio: a linha não salva. Usar o nome do cargo no lugar da atividade (o cargo é outra coluna).', 21),
 ('prod.posto.cargo', 'Cargo', 'A função do quadro que ocupa o posto. Digite para buscar: a lista traz todas as funções do ponto da planta, com a quantidade de pessoas ao lado.', 'Ao escolher, o sistema usa o cargo de mesmo nome (ou cria um) e liga a função ao ponto; é essa ligação que faz as horas do ponto contarem para o posto, e pelo cargo chega-se ao salário base. O kg/homem-hora de hoje lê o ponto por departamento, não o cargo do posto.', 'AJUDANTE DE PRODUÇÃO I (DESOSSA) · 23', 'Função que não aparece: ela só existe na lista se há colaborador com essa função no ponto da planta (confira a conexão do ponto).', 22),
 ('prod.posto.turno_horario', 'Turno e horário', 'Quando o posto trabalha: horário de entrada e de saída (ou um turno da planta). Clique para escolher uma entrada comum do ponto ou digitar.', 'Cria o quadro de turno do posto. Sem quadro de turno em nenhum posto a faixa avisa "Ainda não dá para medir". As horas previstas do posto = saída − entrada. O kg/homem-hora de hoje usa as horas reais do ponto, não este quadro.', '06:00 às 15:48', 'Informar pessoas sem horário: o quadro só nasce com horário ou turno — a tela avisa.', 23),
 ('prod.turno.entrada', 'Entrada do turno', 'Hora em que o posto começa.', 'Com a saída, define as horas previstas do posto no quadro de turno.', '06:00', 'Trocar entrada e saída (saída antes da entrada).', 24),
 ('prod.turno.saida', 'Saída do turno', 'Hora em que o posto termina.', 'Com a entrada, define as horas previstas do posto no quadro de turno.', '15:48', 'Esquecer a saída: o quadro existe, mas sem horas previstas.', 25),
 ('prod.turno.turno_planta', 'Turno da planta', 'Opcional: escolha um turno já cadastrado na planta; entrada e saída vêm dele.', 'Reaproveita um turno da planta em vez de criar outro com o mesmo horário.', 'T0600', 'Escolher o turno e depois mudar a entrada à mão: passa a valer o horário digitado.', 26),
 ('prod.posto.pessoas', 'Pessoas', 'Quantas pessoas o posto tem no turno. Só vale junto com um horário.', 'Fica no quadro de turno (horas-homem previstas = pessoas × horas). O kg/homem-hora de hoje conta as pessoas reais do ponto por dia, não este número.', '4', 'Preencher pessoas e deixar o horário vazio: o quadro não é criado.', 27),
 ('prod.posto.capacidade', 'Cap./h', 'Quanto o posto processa por hora, na unidade de entrada do fluxo. Em branco = a medir (nunca zero).', 'Fica cadastrada no posto como capacidade medida. O indicador de hoje não usa a capacidade; ela é a base para meta e gargalo nas próximas fases.', '420 (kg/h)', 'Digitar 0 para "não sei": deixe em branco — zero seria um dado falso.', 28),
 ('prod.posto.centro_custo', 'Centro de custo', 'O código ou nome do centro de custo do posto, se a empresa usa.', 'Só cadastro por enquanto: não entra no cálculo de indicador.', '3.01 Desossa', 'Inventar um centro que não existe na contabilidade.', 29),
 ('prod.posto.supervisor', 'Supervisor', 'Nome de quem responde pelo posto.', 'Só cadastro por enquanto: não entra no cálculo de indicador.', 'Marcos Silva', 'Colocar o cargo em vez do nome da pessoa.', 30),
 ('prod.posto.categoria', 'Categoria do produto', 'O grupo de produtos que o posto trabalha (criado em ⚙ Cadastros › Categorias de produto).', 'Liga o posto aos produtos agrupados do ATAK. O indicador de hoje soma a produção do setor inteiro, sem separar por categoria.', 'Miúdos', 'Achar que o domínio do ATAK é a categoria: quem decide o agrupamento é você.', 31),
 ('prod.posto.tipo', 'Tipo do posto', 'A natureza do posto, da lista de tipos da planta.', 'Só cadastro por enquanto: não entra no cálculo de indicador.', 'Manual', 'Deixar para depois sem anotar: o tipo ajuda a filtrar postos mais à frente.', 32),
 ('prod.posto.unidade', 'Unidade que conta', 'A unidade em que a produção do posto é contada.', 'Só cadastro por enquanto: o indicador de hoje usa QTDE_KG do ATAK.', 'kg', 'Usar uma unidade diferente da do fluxo sem querer.', 33),
 ('prod.posto.alocacao', 'Alocação', 'Pessoas fixas = sempre as mesmas no posto; rotativas = mudam ao longo do dia.', 'Registra se o quadro do posto é confiável. Com pessoas rotativas, o quadro não representa a realidade — o certo é medir pelo ponto.', 'pessoas fixas', 'Marcar fixa num posto onde o time gira: o quadro vai parecer certo e não será.', 34),
 ('prod.posto.descricao_funcao', 'Descrição da função', 'Texto livre com o que a pessoa do posto faz, passo a passo.', 'Só cadastro por enquanto: não entra no cálculo de indicador.', 'Refila a gordura da alcatra com faca e separa aparas.', 'Repetir a atividade: aqui vai o detalhe.', 35),
 ('prod.posto.arquivar', 'Arquivar posto', 'Clique no × para tirar o posto da lista. Nada é apagado: o posto fica arquivado (ativo = não) e o histórico é mantido.', 'Posto arquivado deixa de contar como posto ativo na faixa "Pronto para medir".', 'Posto que acabou na reorganização da linha.', 'Arquivar para "trocar" o posto: edite o posto em vez de criar outro.', 36),
 ('prod.salario.competencia', 'Competência da folha', 'O mês da folha de onde virão as sugestões de salário.', 'Só escolhe de qual mês a folha sugere o valor. O sistema não calcula nada com isso; quem confirma o valor é você.', '09/2026', 'Usar um mês com rescisões ou muita hora extra: a folha traz o pago, não o base.', 40),
 ('prod.salario.cargo', 'Cargo do salário', 'Cargo a que o salário base se aplica (estimativa enquanto não há alocação nominal).', 'Dá o custo por posto: o posto tem cargo, o cargo tem salário base. LGPD: valor individual só para quem tem permissão de ver salário.', 'Desossador', 'Cadastrar por cargo e por pessoa para o mesmo caso: confira para não duplicar.', 41),
 ('prod.salario.valor', 'Salário base (R$)', 'O salário base mensal, sem hora extra, faltas ou rescisão. Clique no valor para corrigir.', 'É o custo mensal por posto/cargo. O indicador kg/homem-hora de hoje não lê salário; o custo por posto usa este valor.', '2.850,00', 'Usar o pago do mês (com hora extra) como se fosse o base.', 42),
 ('prod.salario.fonte', 'Fonte do salário', 'De onde veio o valor: folha, digitado ou acordo coletivo. Aparece sempre ao lado do valor.', 'Mostra de onde confiar. Ao editar o valor à mão, a fonte passa a "digitado".', 'acordo coletivo', 'Achar que "folha" é salário base: é o pago no mês, confirmado por você.', 43)
) AS v(chave, rotulo, o_que, para_que, exemplo, erro, ordem)
WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'erp_ajuda_campo')
ON CONFLICT (chave) DO NOTHING;
